class AppConstString {
  static const String makeItCount = "MAKE IT COUNT.";
  static const String letsBounz = "LETS BOUNZ";
  static const String loginRegister = "Login or Register";
  static const String kindlyEnterMobileNumber =
      "Kindly Enter Your \nMobile Number";
  static const String noBuzzingAtOdd = "No buzzing at odd hours, promise!";
  static const String continueWith = "Continue with";
  static const String ctn = "Continue";
  static const String submit = "Submit";
  static const String needHelp = "Need Help?";
  static const String cntSupport = "Contact Support";
  static const String enterAmtToCollectBounz = "Enter amount to collect BOUNZ";
  static const String bounzBalance = "BOUNZ Balance";
  static const String google = "Google";
  static const String apple = "Apple";
  static const String proceed = "Proceed";
  static const String or = "OR";
  static const String ok = "OK";
  static const String next = "Next";
  static const String save = "Save";
  static const String search = "Search";
  static const String mobileNo = "Mobile Number";
  static const String mobileNoSmiles = "05X XXX XXXX";
  static const String enterMobileNumber = "Enter Mobile Number";
  static const String unitedArabEmirates =
      "Du, Du United arab emirates\nInternet";
  static const String dataValidity = "Data : 5GB | Validity : 28 days";
  static const String aed25 = "AED 25";
  static const String countryCode91 = "+91";
  static const String planDetails = "Plan Details";
  static const String selectPlans = "Select Plans";
  static const String account = "Account";
  static const String pleaseAddComments = "Please add comments, if any";
  static const String partners = "Partners";
  static const String redeemBounz = "Redeem BOUNZ";
  static const String redeemOffer = "Redeem Offer";
  static const String cancel = "Cancel";
  static const String collectBounz = "Collect Bounz";
  static const String overview = "Overview";
  static const String viewBranches = "View Branches";
  static const String viewMore = "View more";
  static const String viewLess = "View less";
  static const String photos = "Photos";
  static const String viewAll = "View All";
  static const String viewDetails = "View Details";
  static const String offers = "Offers";
  static const String viewOffers = "View Offers";
  static const String redeemOffersHere = "Redeem Offers Here";
  static const String purchasedHistory = "Purchase History";
  static const String voucherHistory = "My vouchers";
  static const String buyGiftCards = "Buy Gift Cards";
  static const String offerDetails = "Offer Details";
  static const String back = "Back";
  static const String reset = "Reset";
  static const String apply = "Apply";
  static const String voucherDetail = "Voucher detail";
  static const String purchaseAgain = "Purchase Again";
  static const String noOffers = "No Offers Found!";
  static const String paymentSuccess = "Payment Successful!";
  static const String confirm = "Confirm";
  static const String enterAmountToRedeem = "Enter Amount To Redeem BOUNZ";
  static const String enterTheBillAmount = "Enter The Bill Amount";
  static const String enterAmountToOffer = "Enter Amount To Redeem Offer";
  static const String enterPIN = "Ask Cashier to Enter Their PIN";
  static const String invoiceNumber = "Enter Invoice Number";
  static const String invoiceNoPlaceHolder = "Invoice Number";
  static const String frdName = "Friend's First Name*";
  static const String earnBounz = "EARN BOUNZ";
  static const String communicationPreferences1 = "Communication\nPreferences";
  static const String interestPreferencesUpdated = "Preferences Updated";
  static const String desiredChannelsOfComn =
      "Select desired channels of communication";
  static const String wpConsent = "Whatsapp\nConsent";
  static const String smsConsent = "SMS\nConsent";
  static const String emailConsent = "Email\nConsent";
  static const String done = "Done";
  static const String commonPreferencesSaved =
      "Communication Preferences saved.";
  static const String interestPreferencesSaved =
      "You have a great taste! Your Preferences are saved.";

  static const String payBill = "Pay bills";
  static const String telAndRec = "Telecom and Recharges";
  static const String houseAndMore = "Household and More";
  static const String visitWebsite = "Visit Website";
  static const String termsAndCondition = "Terms & Conditions apply";
  static const String unsubscribeLink =
      "An 'unsubscribe' link will be available in all such messages for withdrawal of consent. Unsubscribing will have no effect on your membership in the program.";
  static const String wantToReciveComm =
      "I want to receive communication related to news, events and promotions by BOUNZ, its related parties and program partners.";
  static const String innerPartnerTxt =
      "It was over three decades ago that the first Choithram Supermarket and Department Store was established in the UAE. Since then, many Choithrams have come up inconvenient locations across the seven Emirates. With its unbeatably high standard of quality and service, Choithrams has become a name synonymous with excellence in the region today.";
  static const String personalDetailsHeader =
      "LET’S GET TO KNOW EACH OTHER BETTER";
  static const String selectGender = "Select your gender*";
  static const String male = "Male";
  static const String female = "Female";
  static const String firstName = "First Name*";
  static const String lastName = "Last Name*";
  static const String email = "Email Id*";
  static const String dob = "Date of Birth*";
  static const String nationality = "Nationality";
  static const String empType = "Employment Type";
  static const String resiCountry = "Resident Country";
  static const String residentCountry = "Resident Country";
  static const String citySelect = "Select City";
  static const String termsAndConditionHeader = 'Terms & Condition';
  static const String tnc1 = "I agree with the terms ";
  static const String tnc2 = "privacy policy";
  static const String tnc3 = " and";
  static const String tnc4 = " terms of services";
  static const String continueButton = "Continue";
  static const String jane = "Hi Jane!";
  static const String janeDoe = "Jane Doe";
  static const String dubai = "Dubai";
  static const String yourBOUNZ = "Your BOUNZ";
  static const String membershipID = "Membership ID";
  static const String intText = '30,000';
  static const String latestPoints =
      'Your latest points will be updated in 20 mins';
  static const String smiles = "Smiles";
  static const String id = "8466257754";
  static const String myBOUNZ = "My BOUNZ";
  static const String digitalReceipts = "Digital Receipts";
  static const String myPurchases = "My Purchases";
  static const String myVouchers = "My Vouchers";
  static const String redeemedOffer = "Redeemed Offer";
  static const String claimRewards = "Claim Rewards";
  static const String communicationPreferences = "Communication Preferences";
  static const String personalizeYourInterest = "Personalize Your Interest";
  static const String rateUs = "Rate Us";
  static const String helpandSupport = "Help and Support";
  static const String selectNumber = "Select Number";
  static const String customerCareCall = "Call";
  static const String termsandConditions = "Terms and Conditions";
  static const String privacyPolicy = "Privacy Policy";
  static const String connectWithText = "Connect with us to know more";
  static const String logOutButton = "Logout";
  static const String deleteAccountButton = "Delete Account";
  static const String myProfile = "MY PROFILE";
  static const String myProfile2 = "My Profile";
  static const String countryCode = "+971";
  static const String mobile = "Mobile Number*";
  static const String change = "Change";
  static const String verify = "Verify";
  static const String emp = "Employment Type";
  static const String bounzLocation = "Where are you using BOUNZ?";
  static const String radioText = "Are you a United Arab Emirate resident?";
  static const String yes = "Yes";
  static const String no = "No";
  static const String viewReceipt = "View Receipt";
  static const String enterOtp = "ENTER OTP TO VERIFY!";
  static const String numberText =
      "Enter the 5 digit code sent on *********1448";
  static const String creditedText = "YOU HAVE BEEN CREDITED";
  static const String bounzCount = "REFERRAL BOUNZ!";
  static const String frdReferText = "Seems like a friend referred you to us!";
  static const String otpVerify1 = "LET’S GET YOUR";
  static const String otpVerify2 = "MOBILE NUMBER VERIFIED!";
  static const String kudos = "KUDOS!";
  static const String profileCreated = "YOUR PROFILE IS FINALLY CREATED!";
  static const String congrats = "CONGRATS     ";
  static const String bounzCountEarn = " YOU EARNED 10 BOUNZ";
  static const String bounzEarnCount = ' YOU EARNED ';
  static const String bounzTxt = ' Bounz';
  static const String preference = "PREFERENCES UPDATED";
  static const String updatePreference = "Update Preference";

  static const String preferenceText =
      "You have a great taste! Your preferences are saved.";

  static const String notificationHeader = "NOTIFICATIONS";
  static const String interest = "My Interest";
  static const String fancyImageText = "Select things you really fancy";
  static const String clearText = "Clear All";
  static const String notificationText =
      "Discover Honk, where you can service your car easily. Earn 4 Cashback in BOUNZ Rewards*";
  static const String noNotificationText = "You don't have any Notifications";
  static const String goBackText = "Go Back To My Account";
  static const String redeemBounzText = "Earn or Redeem BOUNZ";
  static const String scanBarcodeText = "Scan barcode or use OTP";
  static const String getOtp = "Get OTP";
  static const String scanBarcodePopup = "Scan Barcode";
  static const String featuredText = "Featured Offers";
  static const String fashionText = "Fashion";
  static const String offerOfWeek = "OFFER OF THE WEEK";
  static const String viewAllText = "View All";
  static const String moreBounz = "MORE WITH BOUNZ";
  static const String trending = "TRENDING PARTNERS";
  static const String affiliate = "AFFILIATE PARTNERS";
  static const String topStory = "TOP STORIES";
  static const String headingText =
      "Is it profitable to take a loan and put it in savings?";
  static const String readMore = "Read More";
  static const String rewardExchange = "REWARDS EXCHANGE";
  static const String verification = "Verification";
  static const String linkAccountButton = "Link Account";
  static const String exchangeNowButton = "Exchange Now";
  static const String transferring = "Transferring";
  static const String youWillReceive = "You will Receive";
  static const String confirmText = "Confirm?";
  static const String sufficientBal = "You do not have sufficient balance.";
  static const String enterIdText = "Enter Your Mobile Number";
  static const String hintText =
      "Hint: Mobile (05X XXX XXXX) / Fixed (0X XXX XXXX) number";
  static const String enterOtpText = "Enter Your OTP";
  static const String linkAccountText = "Link your Smiles Account to BOUNZ";
  static const String convertButton = "Convert";
  static const String smileCount = "1 BOUNZ = 20 Smiles";
  static const String smilesBalance = "Smiles Balance";
  static const String transferYour = "Transfer your";
  static const String toReceive = "To Receive";
  static const String transfer = "Transfer your";
  static const String exchangeHistory = "EXCHANGE HISTORY";
  static const String bounzToSmile = "BOUNZ To Smiles";
  static const String pointsConversion = "Conversion:";
  static const String pointsReceived = "Received:";
  static const String transactionStatus = "Transaction Status:";
  static const String transactionDate = "Transaction Date:";
  static const String date = " 21 Jan 2023";
  static const String convertYourPoints = "Convert Your Points";
  static const String youReceived = "You Received";
  static const String pointsCredited1 = "Your points will be credited";
  static const String pointsCredited2 = "in your account.";
  static const String newBOUNZBalance = "New BOUNZ Balance";
  static const String newSmilesBalance = "New Smiles Balance";
  static const String selectCategory = "Select Category";
  static const String all = "All";
  static const String aed20 = "AED 20";
  static const String filters = "Filters";
  static const String selectPrice = "Select price";
  static const String confirmed = "Confirmed";
  static const String congratulations = "CONGRATULATIONS";
  static const String congratulationsMsg =
      "CONGRATULATIONS you won voucher worth";
  static const String confirmButton = "Confirm";
  static const String lowToHigh = "Price - Low to High";
  static const String highToLow = "Price - High to Low";
  static const String orderAToZ = "Order A - Z";
  static const String orderZToA = "Order Z - A";
  static const String giftForMyself = "Gift for Myself";
  static const String giftAFriend = "Gift a Friend";
  static const String sortBy = "Sort By";
  static const merchant = 'Merchant';
  static const earned = 'Earned';
  static const redeemed = 'Redeemed';
  static const expiring = 'Expiry';
  static const thisMonth = 'This Month';
  static const myBounz = "MY BOUNZ";
  static const paymentFailed = "Payement Failed!";
  static const paymentFailedDetails =
      "Payment couldn't be processed, Somthing went wrong please try agian later.";
  static const shopAndEarn = "Shop & Earn";
  static const bounzAlreadyEarned = "BOUNZ already earned";
  static const storeLocationError =
      "You should be in 100 Meter radius of\nstore location to earn BOUNZ";
  static const goBack = "Go Back";
  static const goHome = "Go Home";
  static const address = "Address";
  static const transactionAmount = "Transaction amount";
  static const timeOfVisit = "Time Of Visit";
  static const may2023 = "20th May 2023, 09:36 am";
  static const storeName = "Store Name";
  static const youHaveRedeemed = "You have redeemed 833 BOUNZ";
  static const yourTransactionId = "Your Transaction ID is";
  static const goBackToAllBrands = 'Go Back To All Brands';
  static const goBackToAllOffer = 'Go Back To All Offer';
  static const claimRewardsFour = 'CLAIM REWARDS';
  static const enterCouponCode = 'Enter coupon code';
  static const bounzPoints = '100';
  static const credited = 'Your points will be credited \n in your account.';
  static const rateUS = 'RATE US';
  static const how = ' How would you rate our app?';
  static const pleaseSelect = ' Please select your prefered rating';
  static const receipts = 'CHOITHRAMS RECEIPTS';
  static const otpVerify = 'ENTER OTP TO VERIFY!';
  static const enter5digit =
      'Enter the 5 digit code sent on\njane.doe@gmail.com';
  static const resendOTP = 'Resend OTP?';
  static const giftNCards = 'Gift \n Cards';
  static const rechargeMobile = 'Recharge \n Mobile';
  static const electricityBill = 'Electricity \n Bill';
  static const creditCardBill = 'Credit Card \n Bill';
  static const visitStore = 'Visit the store and simply redeem BOUNZ';
  static const storeLocation =
      'You should be in 100 meter radius to the store location to earn BOUNZ';
  static const earnBounz1 =
      'Click below button and browse Choithrams \nwebsite';
  static const earnBounz2 = '100 BOUNZ';
  static const willBeCredited = ' will be credited in your account';
  static const immediately = '       immediately.';
  static const earnBounz3 = 'Allowed for only once per User.';
  static const earnBounz4 =
      'Please share this 4 digit code with the cashier to complete your redemption';
  static const spentAmount = 'Earn 10 BOUNZ per AED 10 spent';
  static const spentAmount2 = 'Earn 5x BOUNZ for every 20 AED\nspent';
  static const choitramsAiPlaza = 'Choitrams AI Shabhat Plaza';
  static const zayed = 'Zayed Bin Sultan Street  •  24 KM Away';
  static const choithrams = 'CHOITHRAMS';
  static const choithrams1 = 'Hamad bin Abdullah Street';
  static const spinWheel = 'Grab your chance to\nwin some Bounz';
  static const spinWheelLucky = 'Spin and wheel and get lucky!';
  static const aedAmount = '(AED 30.3)';
  static const referNEarn = 'REFER AND EARN';
  static const referralCode = 'Referral Code';
  static const offerText =
      'Tap on your interests and we shall send you exciting offers, discounts & latest deals!';
  static const logout = 'Logout';
  static const rate = 'Rate';
  static const mobileRecharge = 'Mobile Recharge';
  static const selectCountry = 'Select Country';
  static const recentRecharge = 'Recent Recharge';
  static const selectState = 'Select State';
  static const selectOperator = 'Select Operator';
  static const checkOut = 'Checkout';
  static const payableText = 'Total Payable';
  static const aedAmount2 = 'AED 27';
  static const mobileNumber = '+971 658935201';
  static const operatorText = 'Du';
  static const changeNumber = 'Change Number';
  static const payWithBounz = 'Pay with BOUNZ (AED 25)';
  static const balance = 'BOUNZ Balance:';
  static const inAed = 'In AED :';
  static const balanceAmount = '9,78,002';
  static const priceBreakUp = 'Price Breakup';
  static const operatorName = 'Du, Du United arab e...';
  static const convenienceFee = 'Convenience fee (Inclusive VAT 5%)';
  static const total = 'Total';
  static const usedBounz = 'BOUNZ Used';
  static const totalPayable = 'Total Payable';
  static const payNow = 'Pay Now';
  static const earnBounzCheckout = 'Earn upto to 2500 BOUNZ';
  static const bounzApplied = 'BOUNZ Applied';
  static const totalBounz = '2500';
  static const processing = 'Processing';
  static const helpNSupport = 'HELP AND SUPPORT';
  static const howCanWeHelpYou = 'How can we help you?';
  static const faq = 'FAQ';
  static const faqText = "FAQ's";
  static const customerCare4 = "Customer Care";
  static const emailUs1 = "Email Us At";
  static const emailUs3 = "Email Us";
  static const country = 'Country';
  static const state = 'State';
  static const elecBoards = 'Electricity Board';
  static const outstandingBill = 'Outstanding Bill';
  static const addNewPreferences = 'Add New Preferences';
  static const partialPaidBill = 'Partial Paid Bill';
  static const payInAdvance = 'Pay In Advance';
  static const advancePayment = 'Advance payment';
  static const youBothEarn = 'You Both Earn';
  static const bounz100 = '100 Bounz';
  static const errorField = 'Required field';
  static const selectTandC = 'Please select terms and condition!';
  static const pleaseSelectGender = 'Please select Gender';
  static const verifyEmailMessage = 'Please verify your email id';
  static const customerTierValue = 'base';
  static const noResultFound = 'No Results Found';
  static const noDataFound = 'No Data Found';
  static const thankyouforBounz = 'Thank you for \nBOUNZing with us!';
  static const goBackToMyAcc = 'Go back to My account';
  static const goBackToOffer = 'Go back to Offers';
  static const gohome = 'Go to home';
  static const goRedeemedOffer = 'Go to Redeemed Offer';
  static const weVlaueYourFeedback = 'We value your feedback';
  static const newExpAwait = 'A new experience awaits!';
  static const noAccess = 'You Do Not Have Access\nTo The BOUNZ APP Currently.';
  static const updateNow = 'Update Now';
  static const skip = 'skip';
  static const noOffersTxt = 'Please try again later';
  static const noOffersFoundTxt = 'No Offers Found';
  static const deLinkAccountText = 'DeLink your account';
  static const conformDeLinkAccountText =
      'Are you sure you want to DeLink your account?';
  static const oopsItsNotYou = "Oops! It's not you, it's us.";
  static const showBarCode1 =
      "Present the barcode to the cashier at checkout to complete your transaction";
  static const forceUpdateDesc =
      'This exciting update feature some minor bug fixes and enhancements, please continue with the update to improve your experience on the app.';

  static const sha1KeyUat =
      "[120, 252, 199, 144, 223, 246, 61, 32, 52, 106, 144, 147, 230, 138, 232, 210, 168, 90, 167, 217]";
  static const sha1KeyProd =
      "[9, 230, 172, 138, 197, 142, 209, 161, 71, 157, 167, 224, 226, 194, 86, 73, 40, 97, 199, 215]";
  // static const sha1KeyCheckUpdates =
  //     "[120, 252, 199, 144, 223, 246, 61, 32, 52, 106, 144, 147, 230, 138, 232, 210, 168, 90, 167, 217]";
  // "[9, 230, 172, 138, 197, 142, 209, 161, 71, 157, 167, 224, 226, 194, 86, 73, 40, 97, 199, 215]";

  static const reasonSmile = "Another Reason to Smile with BOUNZ!";
  static const reasonSmile1 =
      "Convert your Smiles points to BOUNZ, or BOUNZ to Smiles points, within seconds.";
  static const whtSmile =
      "Convert 4000 Smiles to 1000 BOUNZ \nConvert 2000 BOUNZ to 1000 Smiles";
  static const hwSmile =
      "Link your BOUNZ and Smiles account and get started right away";
  static const linkedMsg = "Bounz is linked to Smiles account";
  static const locationWarningMessage = 'Turn on your location service';
  static const conformExitText = 'Are you sure you want to Exit?';
  static const bannerSlidder = 'banner_slidder';
  static const featuredOffers = 'featured_offers';
  static const offerOfTheWeek = 'offer_of_the_week';
  static const moreWithBounz = 'more_with_bounz';
  static const trendingPartners = 'trending_partners';
  static const affiliatePartners = 'affiliate_partners';
  static const topStories = 'top_stories';
  static const referAFriend = 'refer_a_friend';
  static const growNow = 'grow_now';
  static const backgroundColor = 'background_color';
  static const fontColor = 'font_color';
  static const hoverColor = 'hover_color';
  static const hoverBackgroundColor = 'hover_background_color';
  static const backgroundImage = 'background_image';
  static const themeOnCollapse = 'theme_on_collapse';
  static const image = 'image';
  static const external = 'external';
  static const website = 'website';
  static const slider = 'slider';
  static const grid = 'grid';
  static const partnerDetails = 'Partner Details';
  static const offersDetails = 'Offers Details';
  static const travel = 'Travel';
  static const giftCards = 'Gift Cards';
  static const rechargeMobileN = 'Recharge Mobile';
  static const electricityBillN = 'Electricity Bill';

  // shared pref keys
  static const cacheDatePrefKey = 'cacheDate';
  static const dashboardDataPrefKey = 'dashboardData';
  static const bounzVal = 'BOUNZ';
  static const tempMembershipVal = '6885691752';
  static const tempSmileVal = '0564770522';
  static const smilesVal = 'SMILES';
  static const noInternet = 'No Internet';
  static const internetError = 'Please check your internet connection !!';

  static const imageStored = 'Image stored in gallery';
  static const success = 'Success';
  static const error = 'Error';
  static const couponCode = 'Coupon Code';
  static const description = 'DESCRIPTION';
  static const voucherReceived = 'Voucher received';
  static const voucherExpiry = 'Voucher expiry';
}
